### ISSUE TITLE
点击URL请求后台接口问题

### ISSUE THREAD

**Issue by cykk** [Echosong/beego_blog#1]
你好，我想问下，
{ id: 3, pid: 2, node: '&nbsp;&nbsp;&nbsp;分类管理', url: '/admin/category.html' },
为什么点击这个URL会请求到后台接口，怎么处理的？
谢谢

**Comment by Echosong** [comment]
router.go 里面 
beego.AutoRouter(&controllers.AdminController{})
做的路由，其实 写成 /admin/category 也可以，默认可以加.html 你可以看下beego 的路由

**Comment by cykk** [comment]
好的，多谢
