### ISSUE TITLE
How to change the password of the account of the admin?

### ISSUE THREAD

**Issue by lim-yoona** [Echosong/beego_blog#7]
The default password is too simple to be broken.

**Comment by palp1tate** [comment]
用这个函数生成密码插到你的数据库中：
![image](https://github.com/Echosong/beego_blog/assets/120303802/b81109e8-5b8d-4d54-b05f-9e3c174cd815)

**Comment by lim-yoona** [comment]
> 用这个函数生成密码插到你的数据库中： ![image](https://user-images.githubusercontent.com/120303802/258622045-b81109e8-5b8d-4d54-b05f-9e3c174cd815.png)

Thank u
