### ISSUE TITLE
联系方式

### ISSUE THREAD

**Issue by vcworlds** [Echosong/beego_blog#8]
联系方式可以给一下吗，那个qq搜不到

**Comment by Echosong** [comment]
313690636或者加群



---Original---
From: ***@***.***&gt;
Sent at: 2023年11月7日(Tue) PM4:38
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Echosong/beego_blog] 联系方式 (Issue #8)




 
联系方式可以给一下吗，那个qq搜不到

**Comment by Echosong** [comment]
请问什么事情 QQ应该可以加的



---Original---
From: ***@***.***&gt;
Sent at: 2023年11月7日(Tue) PM4:38
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Echosong/beego_blog] 联系方式 (Issue #8)




 
联系方式可以给一下吗，那个qq搜不到

**Comment by vcworlds** [comment]
搜索不到啊，你挂的那个qq也搜索不到
